export type GenesisVoiceInputMode = "TEXT" | "SPEECH";
export type GenesisVoiceOutputMode = "TEXT" | "SPEECH";
export interface GenesisVoicePreferences { participantId:string; inputMode:GenesisVoiceInputMode; outputMode:GenesisVoiceOutputMode; voiceEnabled:boolean; autoPlayResponses:boolean; language?:string; locale?:string; voiceId?:string; speechRate?:number; volume?:number; updatedAt:string; }
export function createGenesisVoicePreferences(input:{participantId:string;inputMode?:GenesisVoiceInputMode;outputMode?:GenesisVoiceOutputMode;voiceEnabled?:boolean;autoPlayResponses?:boolean;language?:string;locale?:string;voiceId?:string;speechRate?:number;volume?:number;updatedAt?:string}):GenesisVoicePreferences{
 if(!input.participantId.trim()) throw new Error("GENESIS voice participant id is required"); validateVoiceSettings(input.speechRate,input.volume);
 return {participantId:input.participantId,inputMode:input.inputMode??"TEXT",outputMode:input.outputMode??"TEXT",voiceEnabled:input.voiceEnabled??false,autoPlayResponses:input.autoPlayResponses??false,language:input.language,locale:input.locale,voiceId:input.voiceId,speechRate:input.speechRate,volume:input.volume,updatedAt:input.updatedAt??new Date().toISOString()};
}
export function updateGenesisVoicePreferences(current:GenesisVoicePreferences,update:Partial<Omit<GenesisVoicePreferences,"participantId"|"updatedAt">>,updatedAt=new Date().toISOString()):GenesisVoicePreferences{validateVoiceSettings(update.speechRate??current.speechRate,update.volume??current.volume);return {...current,...update,participantId:current.participantId,updatedAt};}
export function disableGenesisVoice(current:GenesisVoicePreferences,updatedAt=new Date().toISOString()):GenesisVoicePreferences{return {...current,inputMode:"TEXT",outputMode:"TEXT",voiceEnabled:false,autoPlayResponses:false,updatedAt};}
export function createGenesisSpeechInput(input:{id:string;participantId:string;runId:string;language?:string;locale?:string;audioReference:string;transcript?:string;createdAt?:string}){if(!input.id.trim()||!input.participantId.trim()||!input.runId.trim())throw new Error("GENESIS speech input identity is required");if(!input.audioReference.trim())throw new Error("Audio reference is required");return {...input,transcriptStatus:input.transcript?"AVAILABLE" as const:"PENDING" as const,status:"RECEIVED" as const,createdAt:input.createdAt??new Date().toISOString()};}
export function createGenesisSpeechOutput(input:{id:string;participantId?:string;responseReference:string;language?:string;locale?:string;voiceId?:string;audioReference?:string;createdAt?:string}){if(!input.id.trim()||!input.responseReference.trim())throw new Error("GENESIS speech output identity is required");return {...input,status:"PENDING" as const,createdAt:input.createdAt??new Date().toISOString()};}
function validateVoiceSettings(speechRate?:number,volume?:number):void{if(speechRate!==undefined&&(speechRate<0.5||speechRate>2))throw new Error("Speech rate must be between 0.5 and 2");if(volume!==undefined&&(volume<0||volume>1))throw new Error("Volume must be between 0 and 1");}
