export type LegalDocumentType = "national_id" | "passport" | "driving_license" | "residence_permit" | "refugee_document" | "other";
export interface LegalIdentityInput { legalName:string; documentType:LegalDocumentType; issuingCountryCode:string; documentNumber:string; nationalityCountryCode?:string; residenceCountryCode?:string; }
export function normalizeCountryCode(value:unknown):string{return String(value??"").trim().toUpperCase();}
export function normalizeEmail(value:unknown):string{const v=String(value??"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(v))throw new Error("INVALID_EMAIL");return v;}
export function normalizePhoneE164(value:unknown):string{const v=String(value??"").trim().replace(/[\s().-]/g,"");if(!/^\+[1-9]\d{7,14}$/.test(v))throw new Error("INVALID_PHONE");return v;}
export function validateLegalIdentity(input:LegalIdentityInput):void{if(input.legalName.trim().length<2)throw new Error("LEGAL_NAME_REQUIRED");if(!input.documentNumber.trim())throw new Error("DOCUMENT_NUMBER_REQUIRED");for(const [name,value] of [["issuing",input.issuingCountryCode],["nationality",input.nationalityCountryCode],["residence",input.residenceCountryCode]] as const){if(value!==undefined&&!/^[A-Z]{2}$/.test(normalizeCountryCode(value)))throw new Error("INVALID_"+name.toUpperCase()+"_COUNTRY");}}
export function normalizeLegalIdentity(input:LegalIdentityInput):LegalIdentityInput{validateLegalIdentity(input);return {...input,legalName:input.legalName.trim(),issuingCountryCode:normalizeCountryCode(input.issuingCountryCode),...(input.nationalityCountryCode?{nationalityCountryCode:normalizeCountryCode(input.nationalityCountryCode)}:{}),...(input.residenceCountryCode?{residenceCountryCode:normalizeCountryCode(input.residenceCountryCode)}:{})};}

export type AccessTargetType="PLACE"|"BUILDING"|"FLOOR"|"UNIT"|"RESOURCE"|"SERVICE"|"DIGITAL";
export type AccessMode="PHYSICAL"|"DIGITAL"|"SERVICE"|"RESOURCE"|"CONTEXTUAL"|"TEMPORARY"|"DELEGATED";
export interface Access{ id:string; participantId:string; targetType:AccessTargetType; targetId:string; mode:AccessMode; status:"ACTIVE"|"EXPIRED"|"REVOKED"|"SUSPENDED"; grantedAt:string; effectiveFrom:string; effectiveUntil?:string; authorizationId?:string; purpose?:string; }
export function createAccess(input:Omit<Access,"status"|"grantedAt">&{status?:Access["status"]}):Access{for(const k of ["id","participantId","targetId"] as const)if(!input[k].trim())throw new Error("INVALID_INPUT");const now=new Date().toISOString();const from=input.effectiveFrom??now;if(input.effectiveUntil&&new Date(input.effectiveUntil)<new Date(from))throw new Error("VALIDATION_FAILURE");return {...input,status:input.status??"ACTIVE",grantedAt:now,effectiveFrom:from};}
export function isAccessActive(a:Access,at=new Date().toISOString()):boolean{return a.status==="ACTIVE"&&new Date(at)>=new Date(a.effectiveFrom)&&(!a.effectiveUntil||new Date(at)<new Date(a.effectiveUntil));}
export function revokeAccess(a:Access,at=new Date().toISOString()):Access{return {...a,status:"REVOKED",effectiveUntil:at};}

export type IntegrationOutcome="ACCEPTED"|"REJECTED"|"UNKNOWN";
export type IntegrationFailure="TIMEOUT"|"DEPENDENCY_FAILURE"|"RECONCILIATION_REQUIRED";
export interface ExternalReference{provider:string;reference:string;}
export interface IntegrationRequest{requestId:string;actionId:string;operation:string;correlationId?:string;causationId?:string;idempotencyKey?:string;payload:unknown;}
export interface IntegrationResponse{outcome:IntegrationOutcome;externalReference?:ExternalReference;failure?:IntegrationFailure;receivedAt:string;}
export interface IntegrationAdapter{execute(request:IntegrationRequest):Promise<IntegrationResponse>;}
export interface NormalizedIntegrationResult extends IntegrationResponse{requestId:string;actionId:string;reconciliationRequired:boolean;}
export async function executeIntegration(adapter:IntegrationAdapter,request:IntegrationRequest):Promise<NormalizedIntegrationResult>{if(!request.requestId.trim()||!request.actionId.trim()||!request.operation.trim())throw new Error("INVALID_INPUT");const response=await adapter.execute(request);if(!response.receivedAt.trim())throw new Error("VALIDATION_FAILURE");if(response.outcome==="ACCEPTED"&&response.failure)throw new Error("VALIDATION_FAILURE");if(response.outcome==="UNKNOWN"&&!response.failure)throw new Error("VALIDATION_FAILURE");if(response.failure==="RECONCILIATION_REQUIRED"&&response.outcome!=="UNKNOWN")throw new Error("VALIDATION_FAILURE");if(response.externalReference&&(!response.externalReference.provider.trim()||!response.externalReference.reference.trim()))throw new Error("VALIDATION_FAILURE");return {...response,requestId:request.requestId,actionId:request.actionId,reconciliationRequired:response.outcome==="UNKNOWN"||response.failure==="RECONCILIATION_REQUIRED"};}

export type MigratedOperationState="REQUESTED"|"PENDING"|"STARTED"|"COMPLETED"|"FAILED"|"CANCELLED"|"REJECTED";
export interface MigratedAction{ id:string; actorParticipantId:string; capabilityId:string; authorizationId:string; targetEntityType:string; targetEntityId:string; operation:string; state:MigratedOperationState; requestedAt:string; correlationId?:string; }
export interface MigratedEvent{ id:string; eventType:string; subjectEntityType:string; subjectEntityId:string; actionId:string; actorParticipantId:string; source:string; timestamp:string; correlationId?:string; }
export interface MigratedEvidence{ id:string; evidenceType:string; subjectEntityType:string; subjectEntityId:string; sourceType:string; sourceReference:string; capturedAt:string; verificationStatus:"UNVERIFIED"|"PENDING"|"VERIFIED"|"REJECTED"; }
export interface MigratedAuthorization{ id:string; participantId:string; capabilityId:string; targetEntityType:string; targetEntityId:string; status:"ACTIVE"|"REVOKED"|"EXPIRED"|"SUSPENDED"; effectiveFrom:string; effectiveUntil?:string; contextId?:string; }
export function assertMigratedAuthorization(a:MigratedAuthorization,participantId:string,capabilityId:string,targetType:string,targetId:string,contextId?:string):void{if(a.status!=="ACTIVE"||a.participantId!==participantId||a.capabilityId!==capabilityId||a.targetEntityType!==targetType||a.targetEntityId!==targetId)throw new Error("UNAUTHORIZED");const now=new Date();if(now<new Date(a.effectiveFrom)||(a.effectiveUntil&&now>=new Date(a.effectiveUntil)))throw new Error("UNAUTHORIZED");if(a.contextId&&a.contextId!==contextId)throw new Error("UNAUTHORIZED");}
export function createMigratedAction(input:{id:string;actorParticipantId:string;capabilityId:string;authorization:MigratedAuthorization;targetEntityType:string;targetEntityId:string;operation:string;contextId?:string;correlationId?:string}):MigratedAction{assertMigratedAuthorization(input.authorization,input.actorParticipantId,input.capabilityId,input.targetEntityType,input.targetEntityId,input.contextId);if(!input.operation.trim())throw new Error("INVALID_INPUT");return{id:input.id,actorParticipantId:input.actorParticipantId,capabilityId:input.capabilityId,authorizationId:input.authorization.id,targetEntityType:input.targetEntityType,targetEntityId:input.targetEntityId,operation:input.operation,state:"REQUESTED",requestedAt:new Date().toISOString(),...(input.correlationId?{correlationId:input.correlationId}:{})};}
export function createMigratedEvent(input:{id:string;eventType:string;subjectEntityType:string;subjectEntityId:string;action:MigratedAction;source:string;actorParticipantId:string;correlationId?:string}):MigratedEvent{if(!input.eventType.trim()||!input.source.trim())throw new Error("INVALID_INPUT");return{id:input.id,eventType:input.eventType,subjectEntityType:input.subjectEntityType,subjectEntityId:input.subjectEntityId,actionId:input.action.id,actorParticipantId:input.actorParticipantId,source:input.source,timestamp:new Date().toISOString(),...(input.correlationId?{correlationId:input.correlationId}:{})};}
export function createMigratedEvidence(input:Omit<MigratedEvidence,"capturedAt"|"verificationStatus">&{capturedAt?:string;verificationStatus?:MigratedEvidence["verificationStatus"]}):MigratedEvidence{for(const k of ["id","evidenceType","subjectEntityType","subjectEntityId","sourceType","sourceReference"] as const)if(!input[k].trim())throw new Error("INVALID_INPUT");return{...input,capturedAt:input.capturedAt??new Date().toISOString(),verificationStatus:input.verificationStatus??"UNVERIFIED"};}

export interface ExperienceRequestState{requestId:string;state:"PENDING"|"CONFIRMED"|"FAILED"|"UNAUTHORIZED"|"UNAVAILABLE";action?:MigratedAction;event?:MigratedEvent;error?:string;}
export function pendingExperienceRequest(requestId:string):ExperienceRequestState{return{requestId,state:"PENDING"};}
export function presentMigratedResponse(requestId:string,action:MigratedAction,event:MigratedEvent):ExperienceRequestState{return{requestId,state:"CONFIRMED",action,event};}
export function presentMigratedError(requestId:string,error:unknown):ExperienceRequestState{const code=error instanceof Error?error.message:"TRANSPORT_ERROR";return{requestId,state:code==="UNAUTHORIZED"?"UNAUTHORIZED":"FAILED",error:code};}