export type ConstantynaAdvisorMode = "ECOSYSTEM_EXPLAIN" | "SOLUTION" | "SERVICE" | "OPPORTUNITY" | "STRATEGY";
export interface ConstantynaAdvisorRequest{id:string;participantId?:string;contextId?:string;mode:ConstantynaAdvisorMode;message:string;requestedAction?:string;receivedAt?:string;}
export interface ConstantynaAdvisorResponse{id:string;requestId:string;participantId?:string;contextId?:string;type:"ECOSYSTEM_EXPLANATION"|"SOLUTION_PROPOSAL"|"SERVICE_PROPOSAL"|"OPPORTUNITY"|"STRATEGY";content:string;proposedActions:string[];serviceReferences:string[];evidenceReferenceIds:string[];authorizationRequired:boolean;codeDisclosure:"FORBIDDEN";rebuildAuthority:"NONE";status:"VERIFIED"|"SUPPORTED"|"PROPOSED"|"FAILED";createdAt:string;}
export interface ConstantynaServiceProposal{id:string;requestId:string;participantId?:string;contextId?:string;serviceName:string;purpose:string;providerReference?:string;eligibility?:string;requirements:string[];estimatedCost?:string;serviceArea?:string;proposedActions:string[];authorizationRequired:boolean;status:"PROPOSED"|"ACCEPTED"|"REJECTED"|"EXPIRED";createdAt:string;}
export function createConstantynaAdvisorRequest(input:Omit<ConstantynaAdvisorRequest,"receivedAt">&{receivedAt?:string}):ConstantynaAdvisorRequest{if(!input.id.trim())throw new Error("CONSTANTYNA advisor request id is required");if(!input.message.trim())throw new Error("CONSTANTYNA advisor message is required");return {...input,receivedAt:input.receivedAt??new Date().toISOString()};}
export function createConstantynaAdvisorResponse(input:Omit<ConstantynaAdvisorResponse,"createdAt">&{createdAt?:string}):ConstantynaAdvisorResponse{if(!input.id.trim())throw new Error("CONSTANTYNA advisor response id is required");if(!input.requestId.trim())throw new Error("CONSTANTYNA request id is required");if(!input.content.trim())throw new Error("CONSTANTYNA response content is required");return {...input,codeDisclosure:"FORBIDDEN",rebuildAuthority:"NONE",createdAt:input.createdAt??new Date().toISOString()};}
export function createConstantynaServiceProposal(input:Omit<ConstantynaServiceProposal,"createdAt">&{createdAt?:string}):ConstantynaServiceProposal{if(!input.id.trim())throw new Error("CONSTANTYNA service proposal id is required");if(!input.requestId.trim())throw new Error("CONSTANTYNA request id is required");if(!input.serviceName.trim())throw new Error("Service name is required");if(!input.purpose.trim())throw new Error("Service purpose is required");return {...input,createdAt:input.createdAt??new Date().toISOString()};}
export function canConstantynaAdvisorExecute(authorizationAllowed:boolean,requestedAction?:string):boolean{return Boolean(requestedAction?.trim())&&authorizationAllowed;}
export function isConstantynaCodeDisclosureRequested(message:string):boolean{const value=message.toLowerCase();return["show the code","explain the source code","rebuild the system","rewrite the system","modify the architecture","change the foundation","give me the repository","give me the code"].some((phrase)=>value.includes(phrase));}
